theme: jekyll-theme-leap-day
title: "Python for Mechanical and Aerospace Engineering"
description: "an introduction to Python for mechanical and aerospace engineers & engineering students"
show_downloads: ["true"]
